name = "ai-powered-static-portfolio-worker"
main = "src/index.ts"
compatibility_date = "2025-09-15"

# Build step: compile TS -> worker/dist as ES modules for Wrangler
[build]
command = "npm --prefix worker run build"

[build.upload]
format = "modules"
dir = "worker/dist"

kv_namespaces = [
  { binding = "RATE_LIMIT_KV", id = "$RATE_LIMIT_KV_ID" },
  { binding = "PROJECT_EMBEDDINGS_KV", id = "$PROJECT_EMBEDDINGS_KV_ID" }
]

[env.production]
# production specific overrides (if needed)
