name = "ai-powered-static-portfolio-worker"
main = "dist/index.js"
compatibility_date = "2023-10-26"

# Build step: compile TS -> worker/dist as ES modules for Wrangler
[build]
command = "npm --prefix worker run build"

[env.production]
name = "ai-powered-static-portfolio-worker-production"
# production specific overrides (if needed)

kv_namespaces = [
  { binding = "RATE_LIMIT_KV", id = "${env.RATE_LIMIT_KV_ID}" },
  { binding = "PROJECT_EMBEDDINGS_KV", id = "${env.PROJECT_EMBEDDINGS_KV_ID}" }
]

[env.production.vars]
RATE_LIMIT_KV_ID = "${RATE_LIMIT_KV_ID}"
PROJECT_EMBEDDINGS_KV_ID = "${PROJECT_EMBEDDINGS_KV_ID}"