name: Build & Deploy

on:
  push:
    branches: [main]

jobs:
  build-and-upload-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install frontend deps
        run: npm ci
        working-directory: frontend
      - name: Build frontend
        run: npm run build
        working-directory: frontend
      - name: Upload artifact for Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: frontend/dist

  deploy-frontend:
    needs: build-and-upload-frontend
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
      contents: read
    steps:
      - name: Deploy to Pages
        uses: actions/deploy-pages@v1

  deploy-worker:
    name: Deploy Cloudflare Worker
    needs: deploy-frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install worker deps
        run: npm ci
        working-directory: worker
      - name: Publish Worker using Wrangler
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          workingDirectory: ./worker
        env:
          RATE_LIMIT_KV_ID: ${{ secrets.RATE_LIMIT_KV_ID }}
